export type ProjectStage =
  | "In progress"
  | "Pending / not started"
  | "Approved"
  | "Bids / appraisal"
  | "DPR / proposed";

export type MajorProject = {
  id: string;
  name: string;
  road: string;
  category: "National highway" | "State highway" | "Expressway / bypass";
  stage: Exclude<ProjectStage, "In progress" | "Pending / not started"> | "In progress";
  districts: string[];
  length: string;
  investment: string;
  statusNote: string;
  sourceName: string;
  sourceDate: string;
  sourceUrl: string;
  route: [number, number][];
};

export const majorProjects: MajorProject[] = [
  {
    id: "bhopal-biaora",
    name: "Bhopal–Biaora corridor",
    road: "NH-12 / NH-46 · Four-lane corridor proposal",
    category: "National highway",
    stage: "DPR / proposed",
    districts: ["Bhopal", "Sehore", "Rajgarh"],
    length: "~152 km",
    investment: "DPR / environmental process",
    statusNote: "The official project summary covers four-laning from Bhopal through Sehore to Biaora. Confirm the latest notified alignment before parcel decisions.",
    sourceName: "MP Pollution Control Board · Project EIA summary",
    sourceDate: "Official project document",
    sourceUrl: "https://www.mppcb.mp.gov.in/proc/408Bpl-Bioara-Sum-NH-12-E.pdf",
    route: [[23.2599, 77.4126], [23.2032, 77.085], [23.0203, 76.7221], [23.8892, 76.7337]],
  },
  {
    id: "bhopal-berasia-sironj",
    name: "Bhopal–Berasia–Sironj corridor",
    road: "SH-23 · Widening / improvement proposal",
    category: "State highway",
    stage: "DPR / proposed",
    districts: ["Bhopal", "Vidisha"],
    length: "~120 km",
    investment: "DPR / environmental process",
    statusNote: "The official project summary describes improvement of the Bhopal–Berasia–Sironj state-highway corridor.",
    sourceName: "MP Pollution Control Board · Project EIA summary",
    sourceDate: "Official project document",
    sourceUrl: "https://www.mppcb.mp.gov.in/pdf/Exe_Summ/Exe_Summ_BPLBRSir_Eng.pdf",
    route: [[23.2599, 77.4126], [23.6327, 77.4335], [24.1039, 77.6907]],
  },
  {
    id: "bhopal-ayodhya-bypass",
    name: "Bhopal Ayodhya Bypass service roads",
    road: "NH-46 to NH-146 · Six-lane urban corridor",
    category: "National highway",
    stage: "Approved",
    districts: ["Bhopal"],
    length: "Urban section",
    investment: "₹1,238.59 cr",
    statusNote: "Six-lane service roads approved from Asharam Tiraha to Ratnagiri Tiraha.",
    sourceName: "PIB · Ministry of Road Transport & Highways",
    sourceDate: "29 Feb 2024",
    sourceUrl: "https://www.pib.gov.in/Pressreleaseshare.aspx?PRID=2010054&lang=2&reg=48",
    route: [[23.25, 77.49], [23.28, 77.5], [23.31, 77.48]],
  },
  {
    id: "betul-khandwa-vadodara",
    name: "Hiwarkhedi–Roshni–Ashapur–Rudhy & Deshgaon–Julwaniya",
    road: "NH-347B · Betul–Khandwa–Vadodara corridor",
    category: "National highway",
    stage: "Approved",
    districts: ["Betul", "Khandwa", "Khargone", "Barwani"],
    length: "233.65 km",
    investment: "₹4,415.60 cr",
    statusNote: "Cabinet approval on HAM; includes a 16.2 km greenfield Khargone bypass.",
    sourceName: "PIB · Cabinet Committee on Economic Affairs",
    sourceDate: "03 Jun 2026",
    sourceUrl: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2268359&lang=1&reg=3",
    route: [[21.9, 77.9], [22.18, 76.93], [21.83, 76.35], [21.83, 75.62], [21.86, 75.1]],
  },
  {
    id: "badnawar-timarwani",
    name: "Badnawar–Petlawad–Thandla–Timarwani",
    road: "NH-752D · Delhi–Mumbai Expressway connector",
    category: "National highway",
    stage: "Approved",
    districts: ["Dhar", "Jhabua"],
    length: "80.45 km",
    investment: "₹3,839.42 cr",
    statusNote: "Cabinet-approved four-lane greenfield and brownfield corridor on HAM.",
    sourceName: "PIB · Cabinet Committee on Economic Affairs",
    sourceDate: "10 Mar 2026",
    sourceUrl: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2237568&lang=1&reg=3",
    route: [[23.02, 75.23], [23.0, 74.8], [23.0, 74.58], [22.84, 74.43]],
  },
  {
    id: "boregaon-shahpur",
    name: "Boregaon Buzurg–Shahpur",
    road: "NH-753L · MP–Maharashtra economic corridor",
    category: "National highway",
    stage: "In progress",
    districts: ["Khandwa", "Burhanpur"],
    length: "~47 km",
    investment: "₹944 cr",
    statusNote: "MoRTH reported approximately 85% construction complete in May 2026.",
    sourceName: "PIB · Ministry of Road Transport & Highways",
    sourceDate: "30 May 2026",
    sourceUrl: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2266946&lang=2&reg=48",
    route: [[21.82, 76.45], [21.57, 76.32], [21.31, 76.23]],
  },
  {
    id: "agra-gwalior",
    name: "Agra–Gwalior Greenfield Expressway",
    road: "NH-719D · Six-lane access-controlled corridor",
    category: "Expressway / bypass",
    stage: "In progress",
    districts: ["Morena", "Gwalior"],
    length: "88 km",
    investment: "₹4,613 cr",
    statusNote: "Concession agreement signed by NHAI for BOT (Toll) implementation.",
    sourceName: "PIB · National Highways Authority of India",
    sourceDate: "30 Apr 2025",
    sourceUrl: "https://www.pib.gov.in/PressReleaseIframePage.aspx?PRID=2125590&lang=2&reg=48",
    route: [[27.08, 78.0], [26.49, 77.99], [26.24, 78.12]],
  },
  {
    id: "indore-eastern-bypass",
    name: "Indore Eastern Bypass",
    road: "Six-lane bypass · km 64–116",
    category: "Expressway / bypass",
    stage: "Bids / appraisal",
    districts: ["Indore"],
    length: "62 km",
    investment: "₹2,971 cr",
    statusNote: "Two HAM packages had bids invited; proposals were submitted for CCEA appraisal.",
    sourceName: "NHAI · Bids & clearance dashboard",
    sourceDate: "14 Nov 2025",
    sourceUrl: "https://nhai.gov.in/nhai/sites/default/files/mix_file/Status_of_Projects_where_Bids.pdf",
    route: [[22.62, 75.95], [22.71, 76.02], [22.83, 75.95]],
  },
  {
    id: "ujjain-jhalawar",
    name: "Ujjain–Jhalawar Package 1",
    road: "NH-552G · Four-lane HAM package",
    category: "National highway",
    stage: "Bids / appraisal",
    districts: ["Ujjain", "Agar"],
    length: "44 km",
    investment: "₹1,345 cr",
    statusNote: "Bid-stage project with proposal submitted for CCEA appraisal.",
    sourceName: "NHAI · Bids & clearance dashboard",
    sourceDate: "14 Nov 2025",
    sourceUrl: "https://nhai.gov.in/nhai/sites/default/files/mix_file/Status_of_Projects_where_Bids.pdf",
    route: [[23.18, 75.78], [23.71, 76.01], [23.95, 76.09], [24.27, 76.15]],
  },
  {
    id: "rewa-sidhi",
    name: "Rewa–Churhat–Sidhi widening",
    road: "NH-39 · Four-lane paved-shoulder packages",
    category: "National highway",
    stage: "DPR / proposed",
    districts: ["Rewa", "Sidhi"],
    length: "59.1 km",
    investment: "HAM packages",
    statusNote: "Rewa–Churhat and Churhat–Sidhi sections listed in NHAI's balance-for-award register.",
    sourceName: "NHAI · Balance for Award",
    sourceDate: "01 Apr 2025",
    sourceUrl: "https://nhai.gov.in/nhai/sites/default/files/mix_file/Balance_for_award_04-25.pdf",
    route: [[24.54, 81.3], [24.43, 81.66], [24.39, 81.88]],
  },
  {
    id: "damoh-jabalpur",
    name: "Damoh–Jabalpur widening",
    road: "NH-34 · Two/four-lane paved-shoulder corridor",
    category: "National highway",
    stage: "DPR / proposed",
    districts: ["Damoh", "Jabalpur"],
    length: "~100 km",
    investment: "EPC packages",
    statusNote: "DPR and first 43.5 km construction package listed for award by NHAI.",
    sourceName: "NHAI · Balance for Award",
    sourceDate: "01 Apr 2025",
    sourceUrl: "https://nhai.gov.in/nhai/sites/default/files/mix_file/Balance_for_award_04-25.pdf",
    route: [[23.84, 79.44], [23.58, 79.75], [23.18, 79.99]],
  },
  {
    id: "indore-western-bypass",
    name: "Indore Western Bypass · Package 1",
    road: "Six-lane greenfield bypass",
    category: "Expressway / bypass",
    stage: "Approved",
    districts: ["Indore"],
    length: "34 km",
    investment: "₹1,534.70 cr",
    statusNote: "Package 1 approved on Hybrid Annuity Mode by MoRTH.",
    sourceName: "PIB · Ministry of Road Transport & Highways",
    sourceDate: "29 Feb 2024",
    sourceUrl: "https://www.pib.gov.in/Pressreleaseshare.aspx?PRID=2010054&lang=2&reg=48",
    route: [[22.63, 75.77], [22.72, 75.68], [22.86, 75.73]],
  },
  {
    id: "shahganj-badi",
    name: "Shahganj Bypass–Badi",
    road: "NH-146B · Four-lane Package IV",
    category: "National highway",
    stage: "Approved",
    districts: ["Sehore", "Raisen"],
    length: "41 km",
    investment: "₹776.19 cr",
    statusNote: "Four-laning approved on Hybrid Annuity Mode.",
    sourceName: "PIB · Ministry of Road Transport & Highways",
    sourceDate: "29 Feb 2024",
    sourceUrl: "https://www.pib.gov.in/Pressreleaseshare.aspx?PRID=2010054&lang=2&reg=48",
    route: [[22.84, 77.8], [22.98, 77.99], [23.1, 78.22]],
  },
  {
    id: "chambal-expressway",
    name: "Greenfield Chambal Expressway",
    road: "Interstate four-lane greenfield corridor",
    category: "Expressway / bypass",
    stage: "DPR / proposed",
    districts: ["Sheopur", "Morena", "Bhind"],
    length: "404 km total",
    investment: "DPR stage",
    statusNote: "Consolidated DPR consultancy listed across Madhya Pradesh, Uttar Pradesh and Rajasthan.",
    sourceName: "NHAI · Balance for Award",
    sourceDate: "01 Apr 2025",
    sourceUrl: "https://nhai.gov.in/nhai/sites/default/files/mix_file/Balance_for_award_04-25.pdf",
    route: [[25.66, 76.7], [26.06, 77.14], [26.49, 77.99], [26.57, 78.78]],
  },
];
