// Generated from scripts/data/states-master.json — do not edit by hand.
// regionalLang: the state's own language (null → toggle collapses to EN/हिंदी).

export const stateRegionalLanguage: Record<number, string | null> = {
  1: null,
  2: "te",
  3: null,
  4: "as",
  5: "hi",
  6: null,
  7: "hi",
  8: "gu",
  9: "gu",
  10: "hi",
  11: null,
  12: "gu",
  13: "hi",
  14: "hi",
  15: "ur",
  16: "hi",
  17: "kn",
  18: "ml",
  19: "ml",
  20: "hi",
  21: "mr",
  22: "mni",
  23: null,
  24: "lus",
  25: null,
  26: "or",
  27: "ta",
  28: "pa",
  29: "hi",
  30: "ne",
  31: "ta",
  32: "bn",
  33: "hi",
  34: "hi",
  35: "bn",
  36: "te",
  37: null,
};

export const languageAutonyms: Record<string, string> = {
  hi: "हिंदी",
  as: "অসমীয়া",
  bn: "বাংলা",
  gu: "ગુજરાતી",
  kn: "ಕನ್ನಡ",
  lus: "Mizo ṭawng",
  ml: "മലയാളം",
  mni: "ꯃꯤꯇꯩꯂꯣꯟ",
  mr: "मराठी",
  ne: "नेपाली",
  or: "ଓଡ଼ିଆ",
  pa: "ਪੰਜਾਬੀ",
  ta: "தமிழ்",
  te: "తెలుగు",
  ur: "اردو",
};
